"""initial schema

Revision ID: 8673c74999d9
Revises: bf8638e2bd7a
Create Date: 2026-08-23 01:29:44.425119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8673c74999d9'
down_revision: Union[str, Sequence[str], None] = 'bf8638e2bd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brands', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('categories', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'brand_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_products_available'), table_name='products')
    op.drop_index(op.f('idx_products_brand'), table_name='products')
    op.drop_index(op.f('idx_products_category'), table_name='products')
    op.drop_index(op.f('idx_products_price'), table_name='products')
    op.drop_constraint(op.f('products_price_check'), 'products', type_='check')
    op.alter_column('search_history', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('search_history', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('search_history', 'brand_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('search_history', 'category_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_search_history_searched_at'), table_name='search_history')
    op.drop_index(op.f('idx_search_history_user'), table_name='search_history')
    op.drop_constraint(op.f('search_history_max_price_check'), 'search_history', type_='check')
    op.drop_constraint(op.f('search_history_min_price_check'), 'search_history', type_='check')
    op.drop_constraint(op.f('valid_price_range'), 'search_history', type_='check')
    op.drop_index(op.f('idx_shopping_history_product'), table_name='shopping_history')
    op.drop_index(op.f('idx_shopping_history_user'), table_name='shopping_history')
    op.create_index(op.f('ix_shopping_history_product_id'), 'shopping_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_shopping_history_user_id'), 'shopping_history', ['user_id'], unique=False)
    op.drop_constraint(op.f('shopping_history_quantity_check'), 'shopping_history', type_='check')
    op.alter_column('shopping_items', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('shopping_items', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('shopping_items', 'product_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_shopping_items_product'), table_name='shopping_items')
    op.drop_index(op.f('idx_shopping_items_user'), table_name='shopping_items')
    op.drop_constraint(op.f('shopping_items_quantity_check'), 'shopping_items', type_='check')
    op.alter_column('user_preferences', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_preferences', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_preferences', 'preferred_brands',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('user_preferences', 'preferred_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_preferences', 'preferred_categories',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('user_preferences', 'preferred_brands',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('user_preferences', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('user_preferences', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_check_constraint(op.f('shopping_items_quantity_check'), 'shopping_items', 'quantity > 0::numeric')
    op.create_index(op.f('idx_shopping_items_user'), 'shopping_items', ['user_id'], unique=False)
    op.create_index(op.f('idx_shopping_items_product'), 'shopping_items', ['product_id'], unique=False)
    op.alter_column('shopping_items', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('shopping_items', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('shopping_items', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_check_constraint(op.f('shopping_history_quantity_check'), 'shopping_history', 'quantity > 0::numeric')
    op.drop_index(op.f('ix_shopping_history_user_id'), table_name='shopping_history')
    op.drop_index(op.f('ix_shopping_history_product_id'), table_name='shopping_history')
    op.create_index(op.f('idx_shopping_history_user'), 'shopping_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_shopping_history_product'), 'shopping_history', ['product_id'], unique=False)
    op.create_check_constraint(op.f('valid_price_range'), 'search_history', 'min_price IS NULL OR max_price IS NULL OR min_price <= max_price')
    op.create_check_constraint(op.f('search_history_min_price_check'), 'search_history', 'min_price >= 0::numeric')
    op.create_check_constraint(op.f('search_history_max_price_check'), 'search_history', 'max_price >= 0::numeric')
    op.create_index(op.f('idx_search_history_user'), 'search_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_search_history_searched_at'), 'search_history', ['searched_at'], unique=False)
    op.alter_column('search_history', 'category_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('search_history', 'brand_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('search_history', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('search_history', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_check_constraint(op.f('products_price_check'), 'products', 'price >= 0::numeric')
    op.create_index(op.f('idx_products_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('idx_products_category'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('idx_products_brand'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('idx_products_available'), 'products', ['available'], unique=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('products', 'brand_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('categories', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('brands', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
